# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2019-03-07 13:53+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"


#: ./apps/archive/archive.py:185 ./apps/archive/archive.py:774
msgid "Package doesn't support Public Service Announcements"
msgstr ""

#: ./apps/archive/archive.py:358 ./apps/archive/archive.py:768
#: ./apps/duplication/archive_duplication.py:134
#: ./apps/item_autosave/components/item_autosave.py:38
msgid "The item was locked by another user"
msgstr ""

#: ./apps/archive/archive.py:394 ./apps/archived/archived.py:189
msgid "User does not have permissions to read the item."
msgstr ""

#: ./apps/archive/archive.py:409
msgid "Invalid version {old_version}"
msgstr ""

#: ./apps/archive/archive.py:413
msgid "Invalid item id {item_id}"
msgstr ""

#: ./apps/archive/archive.py:417
msgid "Invalid last version {last_version}"
msgstr ""

#: ./apps/archive/archive.py:692
msgid "An item can't have both Publish Schedule and Embargo"
msgstr ""

#: ./apps/archive/archive.py:697
msgid "Embargo cannot be earlier than now"
msgstr ""

#: ./apps/archive/archive.py:700
msgid "Rewrites doesn't support Embargo"
msgstr ""

#: ./apps/archive/archive.py:703
msgid "Invalid Embargo"
msgstr ""

#: ./apps/archive/archive.py:707
msgid "A Package doesn't support Embargo"
msgstr ""

#: ./apps/archive/archive.py:771
msgid "Item isn't in a valid state to be updated."
msgstr ""

#: ./apps/archive/archive.py:779
msgid "Unauthorized to modify Unique Name"
msgstr ""

#: ./apps/archive/archive.py:784
msgid "Cannot change the genre for broadcast content."
msgstr ""

#: ./apps/archive/archive.py:789
msgid "This item is in a package and it needs to be removed before the item can be scheduled!"
msgstr ""

#: ./apps/archive/archive.py:815
msgid "Duplicate category codes are not allowed"
msgstr ""

#: ./apps/archive/archive.py:820
msgid "Duplicate subjects are not allowed"
msgstr ""

#: ./apps/archive/archive.py:958
msgid "Client and server etags don't match"
msgstr ""

#: ./apps/archive/archive.py:960
msgid "Request for Auto-save must have _id"
msgstr ""

#: ./apps/archive/archive_link.py:59 ./apps/archive/archive_rewrite.py:276
msgid "Only updates can be unlinked!"
msgstr ""

#: ./apps/archive/archive_rewrite.py:100
msgid "Cannot find the article"
msgstr ""

#: ./apps/archive/archive_rewrite.py:103
msgid "Rewrite of an Item having embargo isn't possible"
msgstr ""

#: ./apps/archive/archive_rewrite.py:106
msgid "Event id does not exist"
msgstr ""

#: ./apps/archive/archive_rewrite.py:109
msgid "Article has been rewritten before !"
msgstr ""

#: ./apps/archive/archive_rewrite.py:116
msgid "Rewrite is not published. Cannot rewrite the story again."
msgstr ""

#: ./apps/archive/archive_rewrite.py:121
msgid "Rewrite story has been used as update before !"
msgstr ""

#: ./apps/archive/archive_rewrite.py:132
msgid "Rewrite story can only be text or pre-formatted !"
msgstr ""

#: ./apps/archive/archive_rewrite.py:136
msgid "Broadcast cannot be a update story !"
msgstr ""

#: ./apps/archive/archive_rewrite.py:139
msgid "Rewrite item content profile does not match with Original item."
msgstr ""

#: ./apps/archive/archive_spike.py:97
msgid "The item \"{slugline}\" is in a package"
msgstr ""

#: ./apps/archive/archive_spike.py:98
msgid " it needs to be removed before the item can be spiked"
msgstr ""

#: ./apps/archive/common.py:437
msgid "Document not found in archive collection"
msgstr ""

#: ./apps/archive/common.py:544 ./apps/tasks.py:87
msgid "Invalid desk identifier {desk_id}"
msgstr ""

#: ./apps/archive/common.py:550 ./apps/tasks.py:97
msgid "Invalid stage identifier {stage_id}"
msgstr ""

#: ./apps/archive/common.py:626 ./apps/archive/common.py:628
msgid "Schedule date is not recognized"
msgstr ""

#: ./apps/archive/common.py:630
msgid "Schedule cannot be earlier than now"
msgstr ""

#: ./apps/archive_broadcast/broadcast.py:87
msgid "Cannot find the {genre} genre."
msgstr ""

#: ./apps/archive_broadcast/broadcast.py:117
msgid "Cannot find the requested item id."
msgstr ""

#: ./apps/archive_broadcast/broadcast.py:120
msgid "Invalid content type."
msgstr ""

#: ./apps/archive_broadcast/broadcast.py:123
msgid "Invalid content state."
msgstr ""

#: ./apps/archived/archived.py:128
msgid "Only Text articles are allowed to be Killed in Archived repo"
msgstr ""

#: ./apps/archived/archived.py:131
msgid "Killing of Broadcast Items isn't allowed in Archived repo"
msgstr ""

#: ./apps/archived/archived.py:135
msgid "Can't kill as this article acts as a Master Story for existing broadcast(s)"
msgstr ""

#: ./apps/archived/archived.py:138
msgid "Can't Kill as article is still available in production"
msgstr ""

#: ./apps/archived/archived.py:141
msgid "Can't kill as article is part of a Package"
msgstr ""

#: ./apps/archived/archived.py:146
msgid "Can't Kill as the Digital Story is still available in production"
msgstr ""

#: ./apps/archived/archived.py:152
msgid "Digital Story of the article not found in Archived repo"
msgstr ""

#: ./apps/archived/archived.py:156
msgid "Can't kill as Digital Story is part of a Package"
msgstr ""

#: ./apps/archived/archived.py:161
msgid "Can't Kill as Take(s) are still available in production"
msgstr ""

#: ./apps/archived/archived.py:165
msgid "One of Take(s) not found in Archived repo"
msgstr ""

#: ./apps/archived/archived.py:168
msgid "Can't kill as one of Take(s) is part of a Package"
msgstr ""

#: ./apps/auth/__init__.py:66
msgid "Invalid user."
msgstr ""

#: ./apps/auth/db/reset_password.py:83
msgid "Either key:password or email must be provided"
msgstr ""

#: ./apps/auth/db/reset_password.py:101
msgid "Invalid email"
msgstr ""

#: ./apps/auth/db/reset_password.py:105
msgid "User not enabled"
msgstr ""

#: ./apps/auth/db/reset_password.py:109 ./apps/auth/db/reset_password.py:126
msgid "User not active"
msgstr ""

#: ./apps/comments/comments.py:86
msgid "Commenting on behalf of someone else is prohibited."
msgstr ""

#: ./apps/content_filters/content_filter/content_filter_service.py:41
msgid "Content filter has been referenced by subscriber(s) {references}"
msgstr ""

#: ./apps/content_filters/content_filter/content_filter_service.py:49
msgid "Content filter has been referenced by routing scheme(s) {references}"
msgstr ""

#: ./apps/content_filters/content_filter/content_filter_service.py:57
msgid "Content filter has been referenced in {references})"
msgstr ""

#: ./apps/content_filters/content_filter/content_filter_service.py:127
msgid "Circular dependency error in content filters:{filter}"
msgstr ""

#: ./apps/content_filters/content_filter/content_filter_test.py:48
msgid "Content filter not found"
msgstr ""

#: ./apps/content_filters/content_filter/content_filter_test.py:56
#: ./apps/products/product_test.py:52 ./apps/publish/formatters/service.py:69
msgid "Article not found!"
msgstr ""

#: ./apps/content_filters/content_filter/content_filter_test.py:61
msgid "Error in testing article: {error}"
msgstr ""

#: ./apps/content_filters/content_filter/content_filter_test.py:75
msgid "Error in testing archive: {error}"
msgstr ""

#: ./apps/content_filters/filter_condition/filter_condition_field.py:53
msgid "Invalid filter conditions field {field}"
msgstr ""

#: ./apps/content_filters/filter_condition/filter_condition_service.py:37
msgid "Filter condition has been referenced in content filter: {references}"
msgstr ""

#: ./apps/content_filters/filter_condition/filter_condition_service.py:51
msgid "Filter condition:{condition} has unidentified field: {field}"
msgstr ""

#: ./apps/content_filters/filter_condition/filter_condition_service.py:55
msgid "Filter condition:{condition} has unidentified operator: {operator}"
msgstr ""

#: ./apps/content_filters/filter_condition/filter_condition_service.py:72
msgid "Filter condition:{condition} has identical settings"
msgstr ""

#: ./apps/content_types/content_types.py:132
msgid "Vocabulary {vocabulary} is used in {count} content type(s)"
msgstr ""

#: ./apps/content_types/content_types.py:152
msgid "Cannot disable content profile as following templates are referencing: {templates}"
msgstr ""

#: ./apps/content_types/content_types.py:163
msgid "Cannot disable content profile as following desks are referencing: {desks}"
msgstr ""

#: ./apps/desks.py:206
msgid "Cannot update Desk Type as there are article(s) referenced by the Desk."
msgstr ""

#: ./apps/desks.py:229
msgid "Cannot delete desk as it is assigned as default desk to user(s)."
msgstr ""

#: ./apps/desks.py:240
msgid "Cannot delete desk as routing scheme(s) are associated with the desk"
msgstr ""

#: ./apps/desks.py:253
msgid "Cannot delete desk as it has article(s) or referenced by versions of the article(s)."
msgstr ""

#: ./apps/dictionaries/service.py:144
msgid "A text dictionary file is required"
msgstr ""

#: ./apps/dictionaries/service.py:164
msgid "The dictionary already exists"
msgstr ""

#: ./apps/dictionaries/service.py:188
msgid "User is required for the abbreviations dictionary."
msgstr ""

#: ./apps/dictionaries/service.py:192
msgid "The dictionary type cannot be changed."
msgstr ""

#: ./apps/duplication/archive_copy.py:57
#: ./apps/duplication/archive_duplication.py:123
#: ./apps/duplication/archive_move.py:109
#: ./apps/duplication/archive_translate.py:69
msgid "Fail to found item with guid: {guid}"
msgstr ""

#: ./apps/duplication/archive_copy.py:62
msgid "Copy is not allowed on items in a desk."
msgstr ""

#: ./apps/duplication/archive_fetch.py:77
msgid "Fail to found ingest item with _id: {id"
msgstr ""

#: ./apps/duplication/archive_move.py:75
msgid "Item is locked for move by another user."
msgstr ""

#: ./apps/duplication/archive_move.py:156
msgid "Move is not allowed within the same stage."
msgstr ""

#: ./apps/export/service.py:66
msgid "Error creating export zip file. Try again please."
msgstr ""

#: ./apps/export/service.py:79
msgid "No items to export."
msgstr ""

#: ./apps/export/service.py:84
msgid "Formatter not found for requested format type."
msgstr ""

#: ./apps/io/feeding_services/reuters.py:152
msgid "Not found {payload}"
msgstr ""

#: ./apps/io/search_ingest.py:69
msgid "Destination desk cannot be empty."
msgstr ""

#: ./apps/io/search_ingest.py:111
msgid "provider not found source={source}"
msgstr ""

#: ./apps/item_autosave/components/item_autosave.py:34
msgid "Invalid item identifier"
msgstr ""

#: ./apps/item_lock/components/item_lock.py:76
msgid "Item is locked by another user."
msgstr ""

#: ./apps/item_lock/components/item_lock.py:121
msgid "Item is not locked."
msgstr ""

#: ./apps/keywords/alchemy.py:30
msgid "AlchemyAPI key is not set"
msgstr ""

#: ./apps/keywords/alchemy.py:44
msgid "Fail to connect to Alchemy service"
msgstr ""

#: ./apps/keywords/alchemy.py:50
msgid "Fail to parse the response from Alchemy service"
msgstr ""

#: ./apps/keywords/service.py:28
msgid "Not set a keywords provider"
msgstr ""

#: ./apps/ldap/ldap.py:128
msgid "User does not belong to security Group or could not find the user profile."
msgstr ""

#: ./apps/ldap/ldap.py:177
msgid "No user has been found in AD"
msgstr ""

#: ./apps/ldap/ldap.py:204 ./apps/ldap/ldap.py:211
msgid "Invalid Credentials."
msgstr ""

#: ./apps/ldap/ldap.py:214
msgid "User already exists in the system."
msgstr ""

#: ./apps/packages/package_service.py:134
msgid "Root group is missing."
msgstr ""

#: ./apps/packages/package_service.py:139
msgid "Only one root group is allowed."
msgstr ""

#: ./apps/packages/package_service.py:147
msgid "Group is missing id."
msgstr ""

#: ./apps/packages/package_service.py:158
msgid "{id} group is added multiple times."
msgstr ""

#: ./apps/packages/package_service.py:163
msgid "The number of groups and of referenced groups in the root group do not match."
msgstr ""

#: ./apps/packages/package_service.py:168
msgid "Not all groups are referenced in the root group."
msgstr ""

#: ./apps/packages/package_service.py:213
msgid "Package contains empty ResidRef!"
msgstr ""

#: ./apps/packages/package_service.py:218
msgid "Invalid item reference: {reference}"
msgstr ""

#: ./apps/packages/package_service.py:248
msgid "Trying to self reference as an association."
msgstr ""

#: ./apps/packages/package_service.py:254
msgid "Content associated multiple times"
msgstr ""

#: ./apps/packages/package_service.py:260
msgid "Trying to create a circular reference to: {item_id}"
msgstr ""

#: ./apps/packages/package_service.py:433
msgid "Package can't have item which has embargo. "
msgstr ""

#: ./apps/packages/package_service.py:434
msgid "Slugline/Unique Name of the item having embargo: {slugline}/{unique}"
msgstr ""

#: ./apps/preferences.py:246 ./apps/preferences.py:258
msgid "Invalid preference: {preference}"
msgstr ""

#: ./apps/products/product_test.py:46
msgid "Article id cannot be empty!"
msgstr ""

#: ./apps/products/product_test.py:59
msgid "Error in testing article: {exception}"
msgstr ""

#: ./apps/products/service.py:34
msgid "Product is used by the subscriber(s): {names}"
msgstr ""

#: ./apps/products/service.py:50
msgid "Product is used for API publishing for the subscriber(s): {subscribers}"
msgstr ""

#: ./apps/products/service.py:57
msgid "Product is used for direct publishing for the subscriber(s): {subscribers}"
msgstr ""

#: ./apps/publish/content/common.py:185
#: ./apps/publish/enqueue/enqueue_service.py:199
msgid "Key is missing on article to be published: {exception}"
msgstr ""

#: ./apps/publish/content/common.py:189
msgid "Failed to publish the item: {id}"
msgstr ""

#: ./apps/publish/content/common.py:229
msgid "Embargo can't be set after publishing"
msgstr ""

#: ./apps/publish/content/common.py:233
msgid "Dateline can't be modified on kill or take down"
msgstr ""

#: ./apps/publish/content/common.py:238
msgid "Cannot publish the story after Update is published.!"
msgstr ""

#: ./apps/publish/content/common.py:268 ./apps/publish/content/common.py:327
#: ./apps/publish/enqueue/enqueue_service.py:123
msgid "Corrected package cannot be empty!"
msgstr ""

#: ./apps/publish/content/common.py:272
msgid "Cannot publish an item which is marked as Not for Publication"
msgstr ""

#: ./apps/publish/content/common.py:276
msgid "Can't {operation} as item state is {state}"
msgstr ""

#: ./apps/publish/content/common.py:278
msgid "Can't {operation} as either package state or one of the items state is {state}"
msgstr ""

#: ./apps/publish/content/common.py:320 ./apps/publish/content/publish.py:45
msgid "Empty package cannot be published!"
msgstr ""

#: ./apps/publish/content/common.py:340
msgid "Package item with id: {guid} does not exist."
msgstr ""

#: ./apps/publish/content/kill.py:59
msgid "This item is in a package. It needs to be removed before the item can be killed"
msgstr ""

#: ./apps/publish/content/published_package_items.py:64
msgid "Invalid package identifier"
msgstr ""

#: ./apps/publish/content/published_package_items.py:66
msgid "Package was not published"
msgstr ""

#: ./apps/publish/content/published_package_items.py:73
msgid "Invalid item identifier  {item_id}"
msgstr ""

#: ./apps/publish/content/published_package_items.py:78
msgid "Circular reference in item {item_id}"
msgstr ""

#: ./apps/publish/content/resend.py:62
msgid "No subscribers selected!"
msgstr ""

#: ./apps/publish/content/resend.py:68
msgid "No active subscribers found!"
msgstr ""

#: ./apps/publish/content/resend.py:73
msgid "Only wire subscribers can receive broadcast stories!"
msgstr ""

#: ./apps/publish/content/resend.py:81
msgid "Story couldn't be found!"
msgstr ""

#: ./apps/publish/content/resend.py:85
msgid "Only text stories can be resent!"
msgstr ""

#: ./apps/publish/content/resend.py:90
msgid "Only published, corrected or killed stories can be resent!"
msgstr ""

#: ./apps/publish/content/resend.py:94
msgid "Please use the newest version {version} to resend!"
msgstr ""

#: ./apps/publish/content/resend.py:99
msgid "Updated story cannot be resent!"
msgstr ""

#: ./apps/publish/enqueue/enqueue_service.py:133
msgid "Package item with id: {guid} has not been published."
msgstr ""

#: ./apps/publish/enqueue/enqueue_service.py:203
msgid "Failed to publish the item: {exception}"
msgstr ""

#: ./apps/publish/enqueue/enqueue_service.py:513
msgid "Can not find package {package} published item {item}"
msgstr ""

#: ./apps/publish/formatters/service.py:57
msgid "Formatter name not found"
msgstr ""

#: ./apps/publish/formatters/service.py:62
msgid "Formatter not found"
msgstr ""

#: ./apps/publish/formatters/service.py:83
msgid "Error in formatting article: {exception}"
msgstr ""

#: ./apps/publish/published_item.py:181
msgid "Invalid state ({state}) for the Published item."
msgstr ""

#: ./apps/publish/published_item.py:236 ./apps/publish/published_item.py:248
#: ./apps/publish/published_item.py:260
msgid "Deleting a published item has a workflow which is implemented in remove_expired()."
msgstr ""

#: ./apps/rules/routing_rules.py:204
msgid "Routing scheme is applied to channel(s). It cannot be deleted."
msgstr ""

#: ./apps/rules/routing_rules.py:296
msgid "A Routing Scheme must have at least one Rule"
msgstr ""

#: ./apps/rules/routing_rules.py:303
msgid "A routing rule has invalid fields {fields}"
msgstr ""

#: ./apps/rules/routing_rules.py:309
msgid "A routing rule must have a name"
msgstr ""

#: ./apps/rules/routing_rules.py:312
msgid "A routing rule must have actions"
msgstr ""

#: ./apps/rules/routing_rules.py:331
msgid "Schedule when defined can't be empty."
msgstr ""

#: ./apps/rules/routing_rules.py:335
msgid "Invalid values for day of week."
msgstr ""

#: ./apps/rules/routing_rules.py:341
msgid "Invalid value for from time."
msgstr ""

#: ./apps/rules/routing_rules.py:349
msgid "Invalid value for hour_of_day_to (expected %H:%M:%S)."
msgstr ""

#: ./apps/rules/routing_rules.py:353
msgid "From time should be less than To Time."
msgstr ""

#: ./apps/rules/routing_rules.py:359
msgid "Unknown time zone {time_zone}"
msgstr ""

#: ./apps/rules/routing_rules.py:372
msgid "Rule Names must be unique within a scheme"
msgstr ""

#: ./apps/rules/rule_sets.py:57
msgid "Cannot delete Rule set as it's associated with channel(s)."
msgstr ""

#: ./apps/saved_searches/saved_searches.py:163
msgid "User's subscriptions are not allowed on create"
msgstr ""

#: ./apps/saved_searches/saved_searches.py:188
msgid "Unauthorized to modify subscriptions."
msgstr ""

#: ./apps/saved_searches/saved_searches.py:205
msgid "Unauthorized to modify other users' subscriptions."
msgstr ""

#: ./apps/saved_searches/saved_searches.py:269
msgid "Search cannot be saved without a filter!"
msgstr ""

#: ./apps/saved_searches/saved_searches.py:290
msgid "Fail to validate the filter against {index}."
msgstr ""

#: ./apps/saved_searches/saved_searches.py:309
msgid "Unauthorized to modify other user's local search."
msgstr ""

#: ./apps/saved_searches/saved_searches.py:311
msgid "Unauthorized to modify global search."
msgstr ""

#: ./apps/saved_searches/saved_searches.py:336
msgid "Invalid Saved Search"
msgstr ""

#: ./apps/search_providers/registry.py:31
msgid "fetch_enpoint must be a string"
msgstr ""

#: ./apps/search_providers/registry.py:36
msgid "You have to specify either fetch_endpoint or provider_class."
msgstr ""

#: ./apps/search_providers/registry.py:44
msgid "A Search Provider for the fetch endpoint: {endpoint} exists with name: {name}"
msgstr ""

#: ./apps/search_providers/service.py:72
msgid "Deleting a Search Provider after receiving items is prohibited."
msgstr ""

#: ./apps/stages.py:167
msgid "Cannot delete a Working Stage."
msgstr ""

#: ./apps/stages.py:172
msgid "Cannot delete a Incoming Stage."
msgstr ""

#: ./apps/stages.py:178
msgid "Cannot delete stage as it has article(s) or referenced by versions of the article(s)."
msgstr ""

#: ./apps/stages.py:185
msgid "Stage is referred by Ingest Routing Schemes : {rule_name}"
msgstr ""

#: ./apps/stages.py:205
msgid "Must have one working stage in a desk"
msgstr ""

#: ./apps/stages.py:213
msgid "Must have one incoming stage in a desk"
msgstr ""

#: ./apps/suggestions/service.py:37
msgid "The item identifier is required"
msgstr ""

#: ./apps/suggestions/service.py:42
msgid "Invalid item identifer"
msgstr ""

#: ./apps/tasks.py:130
msgid "Error:{exception} in {rule_type} rule:{rule} for stage:{stage}"
msgstr ""

#: ./apps/templates/content_templates.py:186
msgid "Invalid kill template. {fields} are not allowed"
msgstr ""

#: ./apps/templates/content_templates.py:236
msgid "Kill templates can not be deleted."
msgstr ""

#: ./apps/templates/content_templates.py:324
msgid "Kill templates must be public"
msgstr ""

#: ./apps/templates/content_templates.py:336
msgid "Templates that are not create type can only be assigned to one desk!"
msgstr ""

